name: Update the Main Docs Repository

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-main-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish Documents
        uses: validityBase/docs/publish-docs-action@main
        with:
          docs-repo-access-token: ${{ secrets.DOCS_REPO_ACCESS_TOKEN }}
          source-docs-path: 'docs'
